### ISSUE TITLE
the loopback-sdk-angular module supersedes loopback-angular

### ISSUE THREAD

**Issue by xixilive** [strongloop/gulp-loopback-sdk-angular#7]
NOTE: The loopback-sdk-angular module supersedes loopback-angular. Please update your package.json accordingly.

https://github.com/strongloop/loopback-sdk-angular/blob/master/README.md

**Comment by bajtos** [comment]
@xixilive what are you proposing to change? Could you please contribute the changes yourself and send a pull request?

**Comment by xixilive** [comment]
It seems the modue `loopback-sdk-angular` has rename to `loopback-angular` in npmjs.org registry. and make a redirect from 'github.com/strongloop/loopback-angular' to 'github.com/strongloop/loopback-sdk-angular' in github.

In fact, loopback-angular has different version histories from loopback-sdk-angular

**Comment by xixilive** [comment]
I made a mistake, the loopback-sdk-angular is newer one!

**Comment by bajtos** [comment]
> I made a mistake, the loopback-sdk-angular is newer one!

That's correct :smile: Still, thank you for your caring attitude and the time you invested to make sure this gulp plugin is using the right dependency :clap:
