### ISSUE TITLE
Custom User model not generated properly

### ISSUE THREAD

**Issue by cspeer** [strongloop/gulp-loopback-sdk-angular#8]
Hi,

I'm using `0.1.4` of this package and for some reason my custom `User` model is not generated properly. It looks like it has all the correct properties, but the methods it should have inherited from `User` like `login` are missing.
If I, however, execute the `lb-ng` command myself everything is fine.

As a result I cannot invoke CustomUser.login from my angular controller.

Any ideas to whats going wrong here?

Thanks,
Chris

**Comment by 0candy** [comment]
Please provide a sample repo for me to reproduce this issue:
See link: https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by cspeer** [comment]
Well, I am unable to reproduce the problem on my system now. So I guess either I made a mistake back in September or you changed something which fixed the issue in the meantime.
However, all I did not to try to reproduce the problem was uncomment a few lines in my Gulpfile. Didn't really change anything but it works.
